version: 0.0

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -t ./package
  build:
    commands:
      - cp -r app ./package/
      - cp requirements.txt ./package/
      - cd package && zip -r ../ml-app.zip .

artifacts:
  files:
    - ml-app.zip
